# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20160629_0959'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
