# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0023_auto_20160711_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='option',
        ),
        migrations.AddField(
            model_name='post',
            name='comingback',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='goingat',
            field=models.CharField(default='', max_length=10),
        ),
    ]
