# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0025_auto_20170324_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comingback',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='goingat',
            field=models.CharField(default='', max_length=10),
        ),
    ]
